
# Build Settings
theme: minima # Default GitHub Pages theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
